on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    timeout-minutes: 30

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.label }}

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: windows-latest, r: 'devel'    }
          - {os: windows-latest, r: 'release'  }
#          - {os: macOS-latest,   r: 'devel'    }
          - {os: macOS-latest,   r: 'release'  }
          - {os: ubuntu-latest,  r: 'devel'    }
          - {os: ubuntu-latest,  r: 'release'  }
          - {os: ubuntu-latest,  r: 'oldrel'   }
          - {os: ubuntu-latest,  r: 'oldrel-1' }
          - {os: ubuntu-latest,  r: 'oldrel-2' }
          - {os: ubuntu-latest,  r: '3.5'      }
          - {os: ubuntu-latest,  r: 'release'  , language: ko,    label: ko    }
          - {os: ubuntu-latest,  r: 'release'  , language: zh_CN, label: zh_CN }
          - {os: ubuntu-latest,  r: 'release'  , language: zh_TW, label: zh_TW }
    env:
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## R CMD check
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      _R_CHECK_MATRIX_DATA_: true
      _R_CHECK_SUGGESTS_ONLY_: true
      ## Test in other locale (optional)
      LANGUAGE: ${{ matrix.config.language }}
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y tidy

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      ## Note, R CMD check on R (>= 4.3.0) needs V8
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::V8
          needs: check

      - name: Session info
        run: |
          options(width = 100)
          capabilities()
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check (!Windows)
        if: runner.os != 'Windows'
        run: |
          rcmdcheck::rcmdcheck(
            args = "--as-cran",
            error_on = "note",
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Check (Windows)
        if: runner.os == 'Windows'
        run: |
          rcmdcheck::rcmdcheck(
            path = "r",
            args = c("--no-manual", "--as-cran"),
            error_on = "note",
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
